### ISSUE TITLE
BaseReporter without CONSOLE effect

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/purescript-spec#34]
Maybe we could provide a `BaseReporter` without the `CONSOLE` effect, only doing the pipes machinery, not having default implementations that print to the console. If someone would like to build a reporter for web browsers, or something like the [xUnit reporter](https://github.com/owickstrom/purescript-spec-reporter-xunit/blob/master/src/Test/Spec/Reporter/Xunit.purs#L51), the console effect might not be what you want.

**Comment by felixSchl** [comment]
I think you are referring to the `defaultReporter` implementation since `BaseReporter` does not specify any effects. I agree it would make sense to go for a more conservative default reporter, but what would it do then at all, since all `defaultReporter` does is call the [`reporter`](https://github.com/owickstrom/purescript-spec/blob/master/src/Test/Spec/Reporter/Base.purs#L78-L96) function and you could just do that yourself, `defaultReporter` does not buy you anything here.

**Comment by owickstrom** [comment]
Ah, I see. I'll just use the bare `reporter`, as is, for the Xunit reporter then.
